// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "github.com/nqmt/go-service/domain"
import mock "github.com/stretchr/testify/mock"

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// SaveProduct provides a mock function with given fields: product
func (_m *IRepository) SaveProduct(product *domain.Product) (*domain.Product, error) {
	ret := _m.Called(product)

	var r0 *domain.Product
	if rf, ok := ret.Get(0).(func(*domain.Product) *domain.Product); ok {
		r0 = rf(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Product) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
